INSERT INTO tb_category(name, created_At) VALUES ('Books', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Eletronics', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Tablets', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Celular', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Box Tv', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Web Cam', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Control Game', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Recarregável Bateria', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Raspberry Py', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Books', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Eletronics', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Tablets', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Celular', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Box Tv', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Web Cam', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Control Game', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Recarregável Bateria', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Raspberry Py', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Books', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Eletronics', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Tablets', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Celular', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Box Tv', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Web Cam', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Control Game', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Recarregável Bateria', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Raspberry Py', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Books', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Eletronics', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Tablets', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Celular', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Box Tv', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Web Cam', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Control Game', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Recarregável Bateria', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Raspberry Py', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Books', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Eletronics', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Tablets', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Celular', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Box Tv', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Web Cam', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Control Game', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Recarregável Bateria', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Raspberry Py', NOW());
